# Generated by Django 5.0.3 on 2024-06-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tranzaksiy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='explorer_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
